### ISSUE TITLE
Conflict with new Google Images Design

### ISSUE THREAD

**Issue by ghost** [Catgrills/Hope#3]
Google changed how they show images on Google Images searches. Because of that Hope's style broke, showing images piled up one on top of the other. Google also changed the way they show images once clicked

Image search:

1. Google's design:

![screenshot_151](https://user-images.githubusercontent.com/28932019/49063170-46afad80-f1f5-11e8-9e8e-e1686895da47.png)

2. Hope's conflict

![screenshot_150](https://user-images.githubusercontent.com/28932019/49063128-267fee80-f1f5-11e8-8d17-f59ae46f17bd.png)

Images once clicked

1. Google design

![screenshot_152](https://user-images.githubusercontent.com/28932019/49063351-db1a1000-f1f5-11e8-8750-5ba413e546eb.png)

2. Hope's conflict

![screenshot_153](https://user-images.githubusercontent.com/28932019/49063347-d9e8e300-f1f5-11e8-9809-dbe63aab1387.png)

**Comment by Catgrills** [comment]
Looks like I don't have the new layout enabled yet, so for now I can't solve this issue.

**Comment by milanecode** [comment]
No problem. Please keep us updated if you find a solution for it.
